spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI4FwvfjSycd1APnuG9bjj
      secret-key: O6xaxyiWfSIitcOkSuK27ju4hXT5Hl
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: mall-lzj

  application:
    name: mall-third-party

server:
  port: 40000

rencent:
  sms:
    templateId: 1113672
    SDKAppID: 1400571111
    SDKAppKey: 8bf46fc4da0c752374a688cdc68c0d78
    smsSign: TJISE项目实训
